services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    restart: always

  postgresql:
    image: postgres
    container_name: postgresqldb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: productdb
      PGDATA: /data/postgres_db
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/data/postgres_db
    networks:
      - microservices

volumes:
  mongo:
  postgres:

networks:
  microservices:
    driver: bridge