services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    restart: always

volumes:
  mongo:

networks:
  microservices:
    driver: bridge